### ISSUE TITLE
i am getting import error in 'sudo python manage.py' while installing stacktach on ubuntu 12.04

### ISSUE THREAD

**Issue by PreetiKamble29** [rackerlabs/stacktach#340]
Hello Sir,

I have a fresh ubuntu 12.04. on that i want to install the stacktach. But i am getting error in 'sudo python manage.py'

here is the log of my terminal

demo@demo-OptiPlex-390:~/stacktach$ source stacktach_config.sh
demo@demo-OptiPlex-390:~/stacktach$ python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/validation.py", line 103, in get_validation_errors
    connection.validation.validate_field(e, opts, f)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/validation.py", line 14, in validate_field
    db_version = self.connection.get_server_version()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 415, in get_server_version
    self.cursor().close()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/**init**.py", line 308, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 387, in _cursor
    self.connection = Database.connect(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 193, in **init**
    super(Connection, self).**init**(_args, *_kwargs2)
_mysql_exceptions.OperationalError: (2003, "Can't connect to MySQL server on '192.168.6.10' (111)")
demo@demo-OptiPlex-390:~/stacktach$ sudo python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/**init**.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    **import**(name)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py", line 8, in <module>
    from django.core.management.sql import custom_sql_for_model, emit_post_sync_signal
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/sql.py", line 6, in <module>
    from django.db import models
  File "/usr/local/lib/python2.7/dist-packages/django/db/**init**.py", line 11, in <module>
    if DEFAULT_DB_ALIAS not in settings.DATABASES:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 95, in **init**
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'stacktach.settings' (Is it on sys.path?): No module named settings
demo@demo-OptiPlex-390:~/stacktach$ 

I have installed all the packages listed in pip-requires.txt. I have also done
$ sudo apt-get install mysql-server

$ sudo apt-get install mysql-client

I have also created stacktach database in it.

Still it is giving this error.
## Here is my stacktach_config.sh

export STACKTACH_DB_NAME="stacktach"
export STACKTACH_DB_HOST="192.168.6.10"
export STACKTACH_DB_USERNAME="root"
export STACKTACH_DB_PASSWORD="preeti"
export STACKTACH_DB_PORT="3306"
export STACKTACH_INSTALL_DIR="/home/stacktach/"
export STACKTACH_DEPLOYMENTS_FILE="/home/stacktach/stacktach_worker_config.json"
export STACKTACH_VERIFIER_CONFIG="/home/stacktach/stacktach_verifier_config.json"
## export DJANGO_SETTINGS_MODULE="settings"

Here is sample_local_settings.py in which i have made changes 

---

import os
STACKTACH_DB_ENGINE = 'django.db.backends.mysql'
STACKTACH_DB_NAME = 'stacktach'
STACKTACH_DB_HOST = 'localhost'
STACKTACH_DB_USERNAME = 'stacktach'
STACKTACH_DB_PASSWORD = 'preeti'
STACKTACH_DB_PORT = '3306'
STACKTACH_INSTALL_DIR = os.environ.get('STACKTACH_INSTALL_DIR', '/home/stacktach/')
STACKTACH_DEPLOYMENTS_FILE = os.environ.get('STACKTACH_DEPLOYMENTS_FILE', '/home/stacktach/stacktach_worker_config.json')

---

I have installed Django 1.4.2
Please help me out as soon as possible

**Comment by PreetiKamble29** [comment]
Closing the issue as I am no longer working in this area of subject,
